// Witty status tails (owner request: like OpenClaw's playful lines).
// Generated by the model itself in batches (one cheap call per goal),
// stored in memory/asides.jsonl, rotated at runtime. Fallbacks are
// neutral if the pool is empty — never a hardcoded joke wall.

use serde_json::{json, Value};

fn pool_path(memory_dir: &std::path::Path) -> std::path::PathBuf {
    memory_dir.join("asides.jsonl")
}

/// Pick one aside of a kind; rotates and drops used lines.
pub fn take(memory_dir: &std::path::Path, kind: &str) -> Option<String> {
    let path = pool_path(memory_dir);
    let text = std::fs::read_to_string(&path).ok()?;
    let mut items: Vec<String> = text
        .lines()
        .filter_map(|l| {
            let v: Value = serde_json::from_str(l).ok()?;
            if v.get("kind").and_then(|k| k.as_str()) == Some(kind) {
                v.get("text").and_then(|t| t.as_str()).map(str::to_owned)
            } else {
                None
            }
        })
        .collect();
    if items.is_empty() {
        return None;
    }
    let picked = items.remove(0);
    let rest: Vec<Value> = items.into_iter().map(|t| json!({"kind": kind, "text": t})).collect();
    let others: Vec<Value> = text
        .lines()
        .filter_map(|l| {
            let v: Value = serde_json::from_str(l).ok()?;
            if v.get("kind").and_then(|k| k.as_str()) != Some(kind) {
                Some(v)
            } else {
                None
            }
        })
        .collect();
    let mut out = others;
    out.extend(rest);
    let body: String = out
        .iter()
        .filter_map(|v| serde_json::to_string(v).ok())
        .collect::<Vec<_>>()
        .join("\n");
    let _ = std::fs::write(&path, body + "\n");
    Some(picked)
}

/// Take from the pool or fall back (used at call sites).
pub fn take_or_fallback(memory_dir: &std::path::Path, kind: &str) -> String {
    take(memory_dir, kind).unwrap_or_else(|| fallback(kind))
}

/// Fallback when the pool is dry: neutral, never annoying.
pub fn fallback(kind: &str) -> String {
    match kind {
        "pause" => "holding still".into(),
        "resume" => "back to work".into(),
        _ => "...".into(),
    }
}

/// Prompt for a batch of fresh asides (called by the daemon once per
/// goal, and to refill when a pool runs dry).
pub fn batch_prompt() -> String {
    "Write 10 short concise status tails for an agent named Presence. \
     Format: JSON {\"pause\": [...], \"resume\": [...]}. \
     pause — status after the word Pause (circle paused, waiting for instructions). \
     resume — status after Resuming (circle resumed). \
     Each tail under 6 words, clean engineering tone. Output only JSON."
        .into()
}
